# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da8fde8f5f0a4727662a625feb92c5a163a043dfb1ced32d8a6985afd964eff3f338900c5381b53d033fa34c67077f6edbefb1c09bfd56183a3e50a8288e250c

test:
  secret_key_base: 77323a8e36321c425da216e4bbe1f8dbefe94da45a280bbb652c20ffdaf7c36a1e2d8c0fba96310f432f954c8d84ba2e3ec4080d86e19875b275b0974d96f33d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
